apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: challenge
        image: xpsiron/challenge:latest
        ports:
        - containerPort: 3000