apiVersion: v1
kind: Service
metadata:
  name: challenge
  labels:
    app: challenge
spec:
  type: LoadBalancer
  selector:
    app: challenge 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000